### ISSUE TITLE
Display image response

### ISSUE THREAD

**Issue by thewahome** [microsoftgraph/microsoft-graph-explorer-v2#72]
Firing the my photo request does not show the related profile image response.

##Expected:
Firing a 'my photo' request results in an image being shown in the response component

##Actual results:

* the response contains an empty object
* The photo is not displayed

**Comment by jobala** [comment]
@thewahome 

This happens when the user signs in because the ProfileComponent is using the same actions/reducers as QueryRunner. I am going to give the ProfileComponent it's own reducer and action creator so that signing in doesn't populate the QueryResponse component. Unless this is an expected behavior @darrelmiller  @MIchaelMainer ?

Then add an enhancement for the QueryResponse to show the user's profile picture.

**Comment by MIchaelMainer** [comment]
I wouldn't expect this behavior.

**Comment by thewahome** [comment]
@jobala / @MIchaelMainer  / @darrelmiller ...This: "add an enhancement for the QueryResponse to show the user's profile picture on a my photo request" is exactly what I mean. I will sort the bug on the Profile Component

**Comment by jobala** [comment]
@thewahome  I am adding an issue for the bug in the  Profile Component for tracking.

**Comment by jobala** [comment]
Added the issue [here](https://github.com/microsoftgraph/microsoft-graph-explorer-v2/issues/73)
